### ISSUE TITLE
Zoom clipping issue

### ISSUE THREAD

**Issue by JMVerner** [elusive/diagrammable#16]
If you continue zooming in eventually the diagram "escapes" outside the bounds of the canvas.
![image](https://user-images.githubusercontent.com/33435026/156413559-e369f139-f3d7-4b32-b248-8a67efb01c40.png)

**Comment by JMVerner** [comment]
And perhaps related, if you "pan" the diagram you can pan it outside the canvas as well.
![image](https://user-images.githubusercontent.com/33435026/156413807-7d305212-a588-473e-821f-c281841d00f9.png)

**Comment by elusive** [comment]
Fixed in release 1.0.1
